CM-375: Compare Byte Arrays in .NET (#1164)
* First draft of the article

* Added a set of arrays to compare

* Resolved some conflicts

* Removed PInvoke Test Method, which was throwing an error on Jenkins: "Test method CompareByteArraysInCsharpTests.CompareByteArraysUnitTests.GivenByteArrays_WhenComparedUsingPInvoke_VerifyAccurateResults threw exception:
System.DllNotFoundException: Unable to load shared library 'msvcrt.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. "

* Applying feedback

* Applying the editors' feedback

* Removed a test case

* Simplified the GenerateOrderedArray() function

* Modified the benchmarks to order by arrayName and Mean

* Removed unecessary usings

* Modified the benchmarks to group by arrayName and sort by Mean